### ISSUE TITLE
No python code for RPi

### ISSUE THREAD

**Issue by rwb27** [OpenLabTools/Instruments-MechanicalTester#2]
The code folder only has arduino stuff in it - and we're not sure if it's production or test code...?

**Comment by rob-eager** [comment]
I've added the python framework (code/python/framework.py) and an example test using it (code/python/rxample_test.py)

I've also added the main arduino control sketch - you're quite right that the other code is from testing out different motor options

**Comment by rwb27** [comment]
Brilliant, we'll have a go at testing this today :)

**Comment by rwb27** [comment]
It compiles :)  Haven't done much else with it, but at least we got it on an arduino.  I'll close this for now.
