### ISSUE TITLE
Is there code to find the addresses of the temperature sensors

### ISSUE THREAD

**Issue by rwb27** [OpenLabTools/Instruments-MechanicalTester#3]
@rob-eager mentioned he wrote some code that helped with finding the addresses of the temperature sensors; any chance you've still got it, and if so could you upload it?

Thanks!

**Comment by rob-eager** [comment]
I used the code from here
https://forum.arduino.cc/index.php?topic=143382.0

but there are other address finder scripts out there too.
e.g.
https://www.hacktronics.com/Tutorials/arduino-1-wire-address-finder.html
http://arduino-info.wikispaces.com/Brick-Temperature-DS18B20#mult

**Comment by rwb27** [comment]
Thanks :) I think Valerian has it working now - hopefully we'll take some measurements soon!
